/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : MeCab 996
 #	author : miyako
 #	2013/07/13
 #
 # --------------------------------------------------------------------------------*/



// --- MeCab
void MeCab_GET_KEYWORDS(sLONG_PTR *pResult, PackagePtr pParams);
